# Generated by Django 4.0 on 2021-12-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('year_of_purchase', models.IntegerField()),
                ('number_of_kilometers', models.IntegerField()),
                ('guarantee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id_customer_card', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('cnp', models.CharField(max_length=13)),
                ('date_of_birth', models.DateField()),
                ('date_of_registration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('id_car', models.IntegerField()),
                ('id_customer_card', models.IntegerField()),
                ('sum_of_labor', models.IntegerField()),
                ('sum_of_parts', models.IntegerField()),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
            ],
        ),
    ]
