# Generated by Django 4.0 on 2021-12-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_id',
            new_name='id_car',
        ),
    ]
